name: AWS Code Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: aws-linux-latest

    steps:
    - uses: chrislennon/action-aws-cli@v1.1

    - name: Set AWS region
      run: aws configure set region ap-northeast-1

    - name: Run AWS CodeDeploy
      run: aws deploy create-deployment --application-name "flask_code_deploy" --deployment-group-name "flask_deploy" --github-location repository="super-haker/my-f-app",commitId="${{ github.sha }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}